version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: brolab_postgres_dev
    environment:
      POSTGRES_USER: brolab_user
      POSTGRES_PASSWORD: brolab_password
      POSTGRES_DB: brolab_beats_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brolab_user -d brolab_beats_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: brolab_redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  # Optional: ClamAV for file scanning (if needed for production-like environment)
  clamav:
    image: clamav/clamav:latest
    container_name: brolab_clamav_dev
    ports:
      - "3310:3310"
    restart: unless-stopped
    volumes:
      - clamav_data:/var/lib/clamav
    environment:
      - CLAMD_HOST=0.0.0.0
      - CLAMD_PORT=3310
    profiles:
      - security

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  clamav_data:
    driver: local

networks:
  default:
    name: brolab_network
    driver: bridge
